# Reference-based COMET model (MQM correlated)
type: comet
mode: ref
model: Unbabel/XCOMET-XXL

# If true, try to export error spans when available.
export_error_spans: true

direction: higher_is_better
batch_size: 8
gpus: 1
